def set_env vars
  command = <<~HEREDOC
      echo "Setting Environment Variables"
      source ~/.bashrc
  HEREDOC

  vars.each do |key, value|
    command += <<~HEREDOC
      if [ -z "$#{key}" ]; then
          echo "export #{key}=#{value}" >> ~/.bashrc
      fi
    HEREDOC
  end

  return command
end

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
 # creating a virtual machine ubuntu 
 
 
 
  
  # assign private ip to our VM
  config.vm.network "private_network", ip: "192.168.10.100"   
 
  # Ensure to install hostsupdater plugin on our localhost before rerunning the vagrant
  #config.hostsupdater.aliases = ["development.local"]
 
  # Sync folder from OS to VM
                 # "." means current location - into/inside our VM -
  config.vm.synced_folder ".", "/home/vagrant/app"
  
  # Provisioning
  config.vm.provision "shell", path: "environment/provision.sh"
  app.vm.provision "shell", inline: set_env({ DB_HOST: "mongodb://192.168.10.150:27017/posts" }), privileged: false
end

# setting up db VM
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip: "192.168.10.150"
    #db.hostsupdater.aliases = ["database.local"]
    
    # db proviosioning script available in env/db
    db.vm.synced_folder "environment/db", "/home/vagrant/environment"
    
    # running db script
    db.vm.provision "shell", path: "environment/db/provision.sh", privileged: false
  end
 end
 
